### PR TITLE
Add user settings and key binding templates

### PR DESCRIPTION
**Pull request by petems**
I normally end up copy and pasting my Sublime settings every time I install it on a new machine.

With this, you can keep them in your puppet module for easy installation.

Thanks! :star:

### CODE REVIEW

**Comment by robinvdvleuten** [comment]
:+1: This would be a very nice addition to the module.

**Comment by smerchek** [comment]
:+1:  As soon as I installed the base sublime package, I immediately thought of my need for this feature.

**Comment by petems** [comment]
@wfarr you mind looking at this? Looking at this with fresher eyes, I suppose I should probably make this an optional thing, otherwise every time this is run it might over-write stuff...

**Comment by wfarr** [comment]
@petems Correct. What you've got now will always overwrite.

Set `force => false` and `replace => false`.

**Comment by blackjid** [comment]
I like this, but I would like that the setting were defined in the people manifest.

**Comment by ocxo** [comment]
Not sure this makes sense here as it requires forking the module to make it work. Agree with @blackjid it would make more sense as part of a personal manifest.

**Pull request closed without merging**
